"""empty message

Revision ID: 2c6d276c9188
Revises: 531bcb2465fb
Create Date: 2024-09-11 17:25:28.263846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c6d276c9188'
down_revision = '531bcb2465fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_keyword_assoc',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('keyword_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies_table.id'], name=op.f('fk_company_keyword_assoc_company_id_companies_table')),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords_table.id'], name=op.f('fk_company_keyword_assoc_keyword_id_keywords_table'))
    )
    op.drop_table('company_keyword_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_keyword_association',
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('keyword_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies_table.id'], name='fk_company_keyword_association_company_id_companies_table'),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords_table.id'], name='fk_company_keyword_association_keyword_id_keywords_table')
    )
    op.drop_table('company_keyword_assoc')
    # ### end Alembic commands ###
