"""empty message

Revision ID: 36c6c7551034
Revises: 00d60ea94437
Create Date: 2024-09-30 15:37:11.393211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c6c7551034'
down_revision = '00d60ea94437'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cf_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_cik', sa.Integer(), nullable=False),
    sa.Column('opr_cf', sa.Integer(), nullable=True),
    sa.Column('inv_cf', sa.Integer(), nullable=True),
    sa.Column('fin_cf', sa.Integer(), nullable=True),
    sa.Column('net_cf', sa.Integer(), nullable=True),
    sa.Column('accn', sa.String(), nullable=True),
    sa.Column('start', sa.String(), nullable=True),
    sa.Column('end', sa.String(), nullable=True),
    sa.Column('filed', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('fp', sa.String(), nullable=True),
    sa.Column('frame', sa.String(), nullable=True),
    sa.Column('fy', sa.Integer(), nullable=True),
    sa.Column('op_cf_key', sa.String(), nullable=True),
    sa.Column('inv_cf_key', sa.String(), nullable=True),
    sa.Column('fin_cf_key', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_cik'], ['companies_table.id'], name=op.f('fk_cf_table_company_cik_companies_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cf_table')
    # ### end Alembic commands ###
