"""added comments

Revision ID: 419449ea9e76
Revises: e8dfb5ac52bd
Create Date: 2024-09-11 22:15:29.784665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '419449ea9e76'
down_revision = 'e8dfb5ac52bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies_table.id'], name=op.f('fk_comments_table_company_id_companies_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments_table')
    # ### end Alembic commands ###
