"""empty message

Revision ID: 459f6890389c
Revises: 82e9000d6417
Create Date: 2024-09-10 22:20:03.396192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459f6890389c'
down_revision = '82e9000d6417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assets_current', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assets_noncurrent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('liabilities_current', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('liabilities_noncurrent', sa.Integer(), nullable=True))
        batch_op.drop_column('total_liabilities_current')
        batch_op.drop_column('total_liabilities_noncurrent')
        batch_op.drop_column('total_assets_noncurrent')
        batch_op.drop_column('total_assets_current')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_assets_current', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_assets_noncurrent', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_liabilities_noncurrent', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_liabilities_current', sa.INTEGER(), nullable=True))
        batch_op.drop_column('liabilities_noncurrent')
        batch_op.drop_column('liabilities_current')
        batch_op.drop_column('assets_noncurrent')
        batch_op.drop_column('assets_current')

    # ### end Alembic commands ###
