"""added keyword type

Revision ID: 54537059c4f0
Revises: cd56ba5a3ebf
Create Date: 2024-09-28 15:08:16.954988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54537059c4f0'
down_revision = 'cd56ba5a3ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords_table', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
