"""new income statement

Revision ID: 642cd3aa200e
Revises: df25df65eb5b
Create Date: 2024-10-04 04:47:34.458605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642cd3aa200e'
down_revision = 'df25df65eb5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inc_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interest_and_div_inc_op', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inc_table', schema=None) as batch_op:
        batch_op.drop_column('interest_and_div_inc_op')

    # ### end Alembic commands ###
