"""ifrs revenue

Revision ID: 713c2912250e
Revises: 096f8d627dc2
Create Date: 2024-10-05 21:30:05.690095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713c2912250e'
down_revision = '096f8d627dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inc_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ifrs_revenue', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inc_table', schema=None) as batch_op:
        batch_op.drop_column('ifrs_revenue')

    # ### end Alembic commands ###
