"""empty message

Revision ID: 7f96fb8dbe51
Revises: 4cfcfa058f03
Create Date: 2024-10-03 23:14:49.395278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f96fb8dbe51'
down_revision = '4cfcfa058f03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_stockholders_equity_nci', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('intangible_assets', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.drop_column('intangible_assets')
        batch_op.drop_column('total_stockholders_equity_nci')

    # ### end Alembic commands ###
