"""changed id for balance sheet

Revision ID: 82e9000d6417
Revises: ff37816381b3
Create Date: 2024-09-09 22:18:52.429035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e9000d6417'
down_revision = 'ff37816381b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_liabilities', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_liabilities_and_stockholders_equity', sa.Integer(), nullable=True))
        batch_op.drop_column('total_liabalilities_and_stockholders_equity')
        batch_op.drop_column('total_liabalilities')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_liabalilities', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_liabalilities_and_stockholders_equity', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_liabilities_and_stockholders_equity')
        batch_op.drop_column('total_liabilities')

    # ### end Alembic commands ###
