"""empty message

Revision ID: 9ef20265fb62
Revises: 038652078dea
Create Date: 2024-08-20 22:17:18.433934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef20265fb62'
down_revision = '038652078dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exchange', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_table', schema=None) as batch_op:
        batch_op.drop_column('exchange')

    # ### end Alembic commands ###
