"""add balance sheet

Revision ID: de01648fb075
Revises: b03a7d1a7db4
Create Date: 2024-09-08 14:14:22.231778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de01648fb075'
down_revision = 'b03a7d1a7db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bs_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('accn', sa.String(), nullable=True),
    sa.Column('end', sa.String(), nullable=True),
    sa.Column('filed', sa.String(), nullable=True),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('fp', sa.String(), nullable=True),
    sa.Column('frame', sa.String(), nullable=True),
    sa.Column('fy', sa.Integer(), nullable=True),
    sa.Column('val', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies_table.id'], name=op.f('fk_bs_table_company_id_companies_table')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bs_table')
    # ### end Alembic commands ###
