"""empty message

Revision ID: e8dfb5ac52bd
Revises: 2c6d276c9188
Create Date: 2024-09-11 19:13:04.898524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8dfb5ac52bd'
down_revision = '2c6d276c9188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords_table', schema=None) as batch_op:
        batch_op.drop_constraint('fk_keywords_table_company_id_companies_table', type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keywords_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_keywords_table_company_id_companies_table', 'companies_table', ['company_id'], ['id'])

    # ### end Alembic commands ###
