"""changed id for balance sheet

Revision ID: ff37816381b3
Revises: 35ae881792ee
Create Date: 2024-09-09 17:21:37.810145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff37816381b3'
down_revision = '35ae881792ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_cik', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_bs_table_company_id_companies_table', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bs_table_company_cik_companies_table'), 'companies_table', ['company_cik'], ['id'])
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_bs_table_company_cik_companies_table'), type_='foreignkey')
        batch_op.create_foreign_key('fk_bs_table_company_id_companies_table', 'companies_table', ['company_id'], ['id'])
        batch_op.drop_column('company_cik')

    # ### end Alembic commands ###
