"""empty message

Revision ID: 038652078dea
Revises: fc584859f88d
Create Date: 2024-08-20 21:17:00.255879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '038652078dea'
down_revision = 'fc584859f88d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cik', sa.Integer(), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_table', schema=None) as batch_op:
        batch_op.alter_column('ticker',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('cik')

    # ### end Alembic commands ###
