"""income statement

Revision ID: 03fce2b9c9f9
Revises: 22bb76a261dc
Create Date: 2024-09-23 15:04:50.020452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03fce2b9c9f9'
down_revision = '22bb76a261dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('inc_table',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('company_cik', sa.Integer(), nullable=False),
    # sa.Column('total_revenue', sa.Integer(), nullable=True),
    # sa.Column('accn', sa.String(), nullable=True),
    # sa.Column('end', sa.String(), nullable=True),
    # sa.Column('filed', sa.String(), nullable=True),
    # sa.Column('form', sa.String(), nullable=True),
    # sa.Column('fp', sa.String(), nullable=True),
    # sa.Column('frame', sa.String(), nullable=True),
    # sa.Column('fy', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['company_cik'], ['companies_table.id'], name=op.f('fk_inc_table_company_cik_companies_table')),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('inc_table', schema=None) as batch_op:
    #     batch_op.create_index('idx_company_cik', ['company_cik'], unique=False)

    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inc_table', schema=None) as batch_op:
        batch_op.drop_index('idx_company_cik')

    op.drop_table('inc_table')
    # ### end Alembic commands ###
