"""added company ticker index

Revision ID: 22bb76a261dc
Revises: eab8a5e7da2c
Create Date: 2024-09-16 20:35:05.022974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22bb76a261dc'
down_revision = 'eab8a5e7da2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_table', schema=None) as batch_op:
        batch_op.create_index('idx_ticker', ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_table', schema=None) as batch_op:
        batch_op.drop_index('idx_ticker')

    # ### end Alembic commands ###
