"""cash to bs

Revision ID: 343b8c0206bd
Revises: 7f96fb8dbe51
Create Date: 2024-10-04 01:16:21.878640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '343b8c0206bd'
down_revision = '7f96fb8dbe51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cash', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.drop_column('cash')

    # ### end Alembic commands ###
