"""balance sheet update

Revision ID: 35ae881792ee
Revises: 903d5d0706c5
Create Date: 2024-09-08 19:35:46.220108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ae881792ee'
down_revision = '903d5d0706c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_assets_current', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_assets_noncurrent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_liabilities_current', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_liabilities_noncurrent', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_liabalilities_and_stockholders_equity', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_bs_table_company_cik_companies_table', type_='foreignkey')
        batch_op.drop_column('company_cik')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_cik', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_bs_table_company_cik_companies_table', 'companies_table', ['company_cik'], ['cik'])
        batch_op.drop_column('total_liabalilities_and_stockholders_equity')
        batch_op.drop_column('total_liabilities_noncurrent')
        batch_op.drop_column('total_liabilities_current')
        batch_op.drop_column('total_assets_noncurrent')
        batch_op.drop_column('total_assets_current')

    # ### end Alembic commands ###
