"""balance sheet update

Revision ID: 6447e1b2ca77
Revises: de01648fb075
Create Date: 2024-09-08 14:17:27.601356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6447e1b2ca77'
down_revision = 'de01648fb075'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_assets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_liabalilities', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_stockholders_equity', sa.Integer(), nullable=True))
        batch_op.drop_column('name')
        batch_op.drop_column('val')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('val', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('total_stockholders_equity')
        batch_op.drop_column('total_liabalilities')
        batch_op.drop_column('total_assets')

    # ### end Alembic commands ###
