"""changed comments to notes

Revision ID: 83939d471035
Revises: 2aa349888150
Create Date: 2024-09-13 01:14:11.407822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83939d471035'
down_revision = '2aa349888150'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies_table.id'], name=op.f('fk_notes_table_company_id_companies_table')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('comments_table')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_id', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.VARCHAR(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies_table.id'], name='fk_comments_table_company_id_companies_table'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('notes_table')
    # ### end Alembic commands ###
