"""balance sheet update

Revision ID: 903d5d0706c5
Revises: 6447e1b2ca77
Create Date: 2024-09-08 19:21:12.810044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '903d5d0706c5'
down_revision = '6447e1b2ca77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_cik', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_bs_table_company_cik_companies_table'), 'companies_table', ['company_cik'], ['cik'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bs_table_company_cik_companies_table'), type_='foreignkey')
        batch_op.drop_column('company_cik')

    # ### end Alembic commands ###
