"""empty message

Revision ID: b03a7d1a7db4
Revises: 9ef20265fb62
Create Date: 2024-08-23 17:51:46.720658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b03a7d1a7db4'
down_revision = '9ef20265fb62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cik_10', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies_table', schema=None) as batch_op:
        batch_op.drop_column('cik_10')

    # ### end Alembic commands ###
