"""new income statement

Revision ID: df25df65eb5b
Revises: 53d8f424a27c
Create Date: 2024-10-04 02:40:55.468005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df25df65eb5b'
down_revision = '53d8f424a27c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inc_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rev_from_ceat', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rev_net_of_ie', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rev_from_ciat', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sales_rev_net', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sales_rev_goods_net', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sales_rev_serv_net', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('net_income', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inc_table', schema=None) as batch_op:
        batch_op.drop_column('net_income')
        batch_op.drop_column('sales_rev_serv_net')
        batch_op.drop_column('sales_rev_goods_net')
        batch_op.drop_column('sales_rev_net')
        batch_op.drop_column('rev_from_ciat')
        batch_op.drop_column('rev_net_of_ie')
        batch_op.drop_column('rev_from_ceat')

    # ### end Alembic commands ###
