"""added balance sheet index

Revision ID: eab8a5e7da2c
Revises: 2901b5bf57e1
Create Date: 2024-09-16 20:27:09.440856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eab8a5e7da2c'
down_revision = '2901b5bf57e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.create_index('idx_company_cik', ['company_cik'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bs_table', schema=None) as batch_op:
        batch_op.drop_index('idx_company_cik')

    # ### end Alembic commands ###
